/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author mila_
 */
public class menuPrincipal extends javax.swing.JFrame {

    /** Creates new form menuPrincipal */
    public menuPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FundojLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemServiço = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuOperacao = new javax.swing.JMenu();
        jMenuItemAgenda = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuItemRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FundojLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\mila_\\OneDrive\\Documentos\\NetBeansProjects\\lashShop\\src\\main\\java\\view\\imagens\\icons\\f708df9e37d9f8e416b031b312bc807e.jpg")); // NOI18N
        FundojLabel.setText("jLabel1");

        jMenuCadastro.setText("Cadastro");

        jMenuItemCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\mila_\\OneDrive\\Documentos\\Projeto Java\\BarberShop Material\\View\\imagens\\icons\\cliente-icon.png")); // NOI18N
        jMenuItemCliente.setText("Cliente");
        jMenuCadastro.add(jMenuItemCliente);

        jMenuItemServiço.setIcon(new javax.swing.ImageIcon("C:\\Users\\mila_\\OneDrive\\Documentos\\Projeto Java\\BarberShop Material\\eyelashes-curler.png")); // NOI18N
        jMenuItemServiço.setText("Serviço");
        jMenuItemServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServiçoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemServiço);

        jMenuItemUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\mila_\\OneDrive\\Documentos\\Projeto Java\\BarberShop Material\\View\\imagens\\icons\\usuario-icon.png")); // NOI18N
        jMenuItemUsuario.setText("Usuário");
        jMenuCadastro.add(jMenuItemUsuario);

        jMenuBar1.add(jMenuCadastro);

        jMenuOperacao.setText("Operação");

        jMenuItemAgenda.setIcon(new javax.swing.ImageIcon("C:\\Users\\mila_\\OneDrive\\Documentos\\Projeto Java\\BarberShop Material\\View\\imagens\\icons\\agenda-icon.png")); // NOI18N
        jMenuItemAgenda.setText("Agenda");
        jMenuOperacao.add(jMenuItemAgenda);

        jMenuBar1.add(jMenuOperacao);

        jMenuRelatorio.setText("Relatorio");

        jMenuItemRelatorio.setIcon(new javax.swing.ImageIcon("C:\\Users\\mila_\\OneDrive\\Documentos\\NetBeansProjects\\lashShop\\src\\main\\java\\view\\imagens\\icons\\relatorioTrabalho-icon.png")); // NOI18N
        jMenuItemRelatorio.setText("Relatorio");
        jMenuRelatorio.add(jMenuItemRelatorio);

        jMenuBar1.add(jMenuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FundojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FundojLabel)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServiçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemServiçoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FundojLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemAgenda;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemRelatorio;
    private javax.swing.JMenuItem jMenuItemServiço;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuOperacao;
    private javax.swing.JMenu jMenuRelatorio;
    // End of variables declaration//GEN-END:variables

}
